from collections.abc import Sequence
from typing import Any

def damerau_levenshtein_distance(seq1: Sequence[Any], seq2: Sequence[Any], max_distance: int | None = None) -> int: ...
def normalized_damerau_levenshtein_distance(seq1: Sequence[Any], seq2: Sequence[Any], max_distance: float | None = None) -> float: ...
def damerau_levenshtein_distance_seqs(seq: Sequence[Any], seqs: Sequence[Sequence[Any]], max_distance: int | None = None) -> list[int]: ...
def normalized_damerau_levenshtein_distance_seqs(seq: Sequence[Any], seqs: Sequence[Sequence[Any]], max_distance: float | None = None) -> list[float]: ...
